export const QUESTIONARIO_LABELS: Record<string, string> = {
    instagram: 'Instagram',
    tempoAdvocacia: 'Tempo de Advocacia (anos)',
    tempoPrevidenciario: 'Tempo em Previdenciário (anos)',
    localAtuacao: 'Local de Atuação',
    metaPrincipalNorte: 'Meta Principal (O "Norte")',
    cenarioIdeal12Meses: 'Cenário Ideal (Metas 12 Meses)',
    clientes_novos: 'Novos Clientes/Mês (Meta)',
    clientes_faturamento: 'Faturamento Mensal (Meta)',
    clientes_ticketMedio: 'Ticket Médio (Meta)',
    gestao_equipe: 'Nº Pessoas na Equipe (Meta)',
    gestao_horasTrabalhadas: 'Horas Trabalhadas/Semana (Meta)',
    gestao_metaFinanceira: 'Meta Financeira (Meta)',
    tecnica_metaDominio: 'Meta de Domínio Técnico',
    tecnologia_metaAutomacao: 'Meta de Automação',
    conexoes_metaNetworking: 'Meta de Networking',
    maiorObstaculo: 'Maior Obstáculo',
    autoavaliacao: 'Autoavaliação',
    tecnica: 'Técnica Jurídica',
    captacao: 'Captação de Clientes',
    gestao: 'Gestão',
    tecnologia: 'Tecnologia',
    networking: 'Networking e Autoridade',
    estruturaEquipe: 'Estrutura da Equipe',
    sozinho: 'Atua Sozinho',
    socios: 'Sócio(s)',
    estagiarios: 'Estagiário(s)',
    suporte: 'Equipe de Suporte',
    advogados: 'Advogado(s) Contratado(s)',
    estruturaEquipeContagem: 'Contagem da Equipe',
    equipeComercial: 'Equipe Comercial Dedicada',
    sim: 'Sim',
    nao_eu: 'Não, eu acumulo',
    nao_socio: 'Não, meu sócio acumula',
    nao_secretaria: 'Não, secretária/atendente filtra',
    equipeComercialContagem: 'Nº Pessoas no Comercial',
    desafioGestao: 'Maior Desafio na Gestão',
    estruturaFisica: 'Estrutura Física',
    home_office: 'Home office',
    sala_comercial: 'Sala comercial',
    coworking: 'Coworking',
    outro: 'Outro',
    estruturaFisicaOutro: 'Qual Estrutura Física',
    controleFinanceiro: 'Controle Financeiro',
    nao_controlo: 'Não controlo / Conta pessoal',
    caderno: 'Caderno ou agenda',
    planilha: 'Planilha de Excel',
    software: 'Software de gestão financeira',
    faturamentoMedioMensal: 'Faturamento Médio Mensal',
    ate_5k: 'Até R$ 5.000',
    '5k_10k': 'R$ 5.000 - R$ 10.000',
    '10k_20k': 'R$ 10.000 - R$ 20.000',
    '20k_40k': 'R$ 20.000 - R$ 40.000',
    acima_40k: 'Acima de R$ 40.000',
    sabeCustoFixo: 'Sabe o Custo Fixo Mensal',
    sim_exato: 'Sim, valor exato',
    ideia: 'Tenho uma ideia',
    nao: 'Não',
    custoFixoValor: 'Faixa do Custo Fixo Mensal',
    'ate_2.5k': 'Até R$ 2.500',
    '2.5k_5k': 'R$ 2.500 - R$ 5.000',
    acima_20k: 'Acima de R$ 20.000',
    fonteClientes: 'Principais Fontes de Clientes',
    indicacaoClientes: 'Indicação de clientes',
    indicacaoColegas: 'Indicação de colegas',
    indicacaoParceiros: 'Indicação de parceiros',
    googleMeuNegocio: 'Google Meu Negócio',
    anunciosPagos: 'Anúncios Pagos',
    conteudoOrganico: 'Conteúdo Orgânico',
    atendimentoPresencial: 'Atendimento presencial',
    fonteClientesOutro: 'Outra Fonte de Clientes',
    investeAnuncios: 'Investe em Anúncios Pagos',
    sim_hoje: 'Sim, invisto hoje',
    sim_parei: 'Já investi, mas parei',
    investimentoMedioMensal: 'Investimento Médio Mensal',
    ate_500: 'Até R$ 500',
    '500_1500': 'R$ 500 - R$ 1.500',
    '1500_3000': 'R$ 1.500 - R$ 3.000',
    acima_3000: 'Acima de R$ 3.000',
    motivoNaoInvestir: 'Motivo para Não Investir',
    motivoNaoInvestirOutro: 'Outro Motivo (Não Investe)',
    roi: 'Não tive retorno (ROI)',
    complexo: 'Muito complexo de gerenciar',
    tempo: 'Não tive tempo para dedicar',
    custo: 'Custo muito alto',
    nao_sei: 'Não sei por onde começar',
    plataformasAnuncio: 'Plataformas de Anúncio',
    googleAds: 'Google Ads',
    metaAds: 'Meta Ads',
    plataformasAnuncioOutro: 'Outras Plataformas',
    novosClientesMes: 'Novos Clientes/Mês',
    taxaConversao: 'Taxa de Conversão (a cada 10)',
    responsavelFechamento: 'Responsável pelo Fechamento',
    eu: 'Eu mesmo(a)',
    eu_socio: 'Eu e sócio(a)',
    secretaria: 'Secretária/Atendente',
    vendedor: 'Vendedor(a) dedicado(a)',
    carroChefe: '"Carro-Chefe" Técnico',
    urbanas: 'Aposentadorias Urbanas',
    rurais: 'Aposentadorias Rurais',
    incapacidade: 'Benefícios por Incapacidade',
    planejamento: 'Planejamento Previdenciário',
    rpps: 'RPPS',
    carroChefeOutro: 'Outro "Carro-Chefe"',
    assuntoInseguro: 'Assunto Técnico Inseguro',
    softwareGestao: 'Usa Software de Gestão',
    softwareGestaoQual: 'Qual Software de Gestão',
    acompanhamentoPublicacoes: 'Acompanhamento de Publicações',
    manual: 'Manual',
    gestao_ja_faz: 'Software de gestão já faz',
    pessoa_dedicada: 'Pessoa dedicada',
    nao_estruturado: 'Não estruturado',
    acompanhamentoPublicacoesQual: 'Qual Software de Publicações',
    monitoramentoProcessosADM: 'Monitoramento Processos ADM',
    robo: 'Robô de captura',
    nao_ativo: 'Não monitoro ativamente',
    monitoramentoProcessosADMQual: 'Qual Robô de Monitoramento',
    softwareCalculos: 'Usa Software de Cálculos',
    sim_pago: 'Sim, pago',
    sim_gratuito: 'Sim, gratuito',
    softwareCalculosQual: 'Qual Software de Cálculos',
    usaIA: 'Usa IA (Produtividade/Conteúdo)',
    frequente_juridico: 'Frequente (Jurídico)',
    frequente_gestao: 'Frequente (Gestão/Mkt)',
    raramente: 'Raramente',
    usaIAWhatsappLeads: 'Usa IA para Atendimento de Leads (WhatsApp)',
    usaIAWhatsappLeadsQual: 'Qual Ferramenta de IA para Leads',
    usaIASuporteCliente: 'Usa IA para Suporte ao Cliente',
    usaIASuporteClienteQual: 'Qual Ferramenta de IA para Suporte',
    produzConteudoDigital: 'Produz Conteúdo Digital',
    sim_consistente: 'Sim, consistente',
    sim_raramente: 'Sim, raramente',
    tentei_parei: 'Já tentei, mas parei',
    parceriasAtivas: 'Possui Parcerias Ativas',
    sim_formal: 'Sim, formais',
    contatos_informais: 'Apenas contatos informais',
    fechamento: 'Observações Finais',
};